#!/usr/bin/env bun
// Wire the main HUD into ~/.claude/settings.json. A plugin can't auto-apply the
// main `statusLine` (only `subagentStatusLine`), so run this once after install —
// and again after each `/plugin update`, since a plugin's install path changes
// on every update.
//
//   bun scripts/install-statusline.ts [refreshInterval]
//
// To stay stable across updates, settings.json points at a fixed launcher
// (~/.claude/oh-my-cchud/statusline.sh) that we (re)write to exec THIS checkout.
// So updating the plugin only means re-running this script — settings.json never
// has to change.

import { homedir } from "node:os";
import { join, resolve, dirname } from "node:path";
import {
  readFileSync,
  writeFileSync,
  existsSync,
  copyFileSync,
  mkdirSync,
  chmodSync,
} from "node:fs";

const home = homedir();
const settingsPath = join(home, ".claude", "settings.json");
const root = resolve(dirname(new URL(import.meta.url).pathname), "..");
const refreshInterval = Number(process.argv[2] ?? 2);

// Prefer the compiled binary (no `bun` on PATH needed); else run the TS entry.
const binary = join(root, "dist", "cchud");
const execLine = existsSync(binary)
  ? `exec ${JSON.stringify(binary)} "$@"`
  : `exec bun ${JSON.stringify(join(root, "src", "statusline.ts"))} "$@"`;

// Stable launcher → settings.json points here and never changes across updates.
const launcherDir = join(home, ".claude", "oh-my-cchud");
mkdirSync(launcherDir, { recursive: true });
const launcher = join(launcherDir, "statusline.sh");
writeFileSync(
  launcher,
  `#!/bin/sh\n# generated by oh-my-cchud — re-run scripts/install-statusline.ts after /plugin update\n${execLine}\n`,
);
chmodSync(launcher, 0o755);

let settings: Record<string, any> = {};
if (existsSync(settingsPath)) {
  try {
    settings = JSON.parse(readFileSync(settingsPath, "utf8"));
    copyFileSync(settingsPath, settingsPath + ".bak"); // back up before editing
  } catch {
    console.error(`Could not parse ${settingsPath}; aborting.`);
    process.exit(1);
  }
} else {
  mkdirSync(dirname(settingsPath), { recursive: true });
}

settings.statusLine = { type: "command", command: launcher, refreshInterval };
writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n");

const target = execLine.replace(/^exec /, "").replace(/ "\$@"$/, "");
console.log(`✓ oh-my-cchud wired into ${settingsPath}`);
console.log(`  statusLine → ${launcher}`);
console.log(`  launcher exec → ${target}`);
console.log(`  refreshInterval: ${refreshInterval}s`);
if (existsSync(settingsPath + ".bak")) console.log(`  (backup: ${settingsPath}.bak)`);
console.log(`\nOpen a new Claude Code prompt to see the HUD.`);
